### PR TITLE
Add switch to hide up-to-date exercises

### LINKED ISSUE #16: Add switch to hide up-to-date exercises
https://github.com/exercism/exercism/issues/5056

### PR DESCRIPTION
**Pull request by trblackw**
resolves #16 

NOTE: During this process I was running into a sporadic TS error occurring in the `useLocation` hook. I made sure it wasn't resulting from any changes I made lol. Specifically the type definition for `oldTrigger` in the `originalHistoryTriggers` function. However, I can't get it to consistently occur, which is confusing.

Resulting error (in FF):
image

### CODE REVIEW

**Comment by trblackw** [comment]
Also, let me know if you want me to move the toggler placement. I just put it where I thought it made sense at the top next to the change track button

**Comment by SleeplessByte** [comment]
Yeah, it's an interesting one. It should really not complain about it. I have seen it too. I'll probably fix it by casting that map to `any` first ;). My initial guess is that it's about the load order of the types and that there is a History definiton that it doesn't like.

Needless to say: we don't use `this` in those functions ourselves, so it's a non-issue.

**Comment by SleeplessByte** [comment]
Check-out my changes! I basically extracted the state you used into a context, and applied what you did to the views as well.

**Comment by SleeplessByte** [comment]
It's live! Here is a good example: https://tracks.exercism.io/ocaml/master

**Pull request merged**
